CREATE TABLE TPCUSTOMER (
  CUSTOMER_ID INT PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(255),
  CUSTOMER_EMAIL VARCHAR(255),
  CUSTOMER_PHONE     VARCHAR(10));

Alter table tpcustomer modify column CUSTOMER_Phone varchar(15);

CREATE TABLE TPWAREHOUSE(
  WAREHOUSE_ID INT PRIMARY KEY,
  WAREHOUSE_NAME    VARCHAR(38),
  WAREHOUSE_LOCATION   VARCHAR(50)
);


CREATE TABLE TPSUPPLIER (
  SUPPLIER_ID  INT PRIMARY KEY,
  SUPPLIER_NAME   VARCHAR(255) NOT NULL,
  SUPPLIER_PHONE  VARCHAR(10)
);
alter table tpsupplier modify column SUPPLIER_PHONE varchar(15);

CREATE TABLE TPDEPARTMENT(
  DEPARTMENT_ID INT,
  EMPLOYEE_ID INT,
  DEPARTMENT_HEAD VARCHAR(20),
  DEPARTMENT_NAME   VARCHAR(25),
  DEPARTMENT_PHONE    VARCHAR(10),
  PRIMARY KEY (DEPARTMENT_ID, EMPLOYEE_ID)
);

CREATE TABLE TPPAYMENTS (
  PAYMENT_ID INT PRIMARY KEY,
  CUSTOMER_ID   INT,
  PAYMENT_METHOD VARCHAR(10),
  PAYMENT_AMOUNT NUMERIC(20,2),
  PAYMENT_DATE DATE,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES TPCUSTOMER(CUSTOMER_ID)
);

CREATE TABLE TPPRODUCT_TYPE(
  P_TYPE_ID INT PRIMARY KEY,
  PRODUCT_TYPE    VARCHAR(38));



CREATE TABLE TPPRODUCT (
  PRODUCT_ID INT PRIMARY KEY,
  SUPPLIER_ID INT,
  WAREHOUSE_ID INT,
  P_TYPE_ID INT,
  PRODUCT_NAME VARCHAR(50) NOT NULL,
  PRODUCT_PRICE INT,
  FOREIGN KEY (SUPPLIER_ID) REFERENCES TPSUPPLIER(SUPPLIER_ID),
  FOREIGN KEY (WAREHOUSE_ID) REFERENCES TPWAREHOUSE(WAREHOUSE_ID),
  Foreign key (P_TYPE_ID) REFERENCES tpproduct_type (P_TYPE_ID));

drop table tpproduct;

CREATE TABLE TPEMPLOYEE (
  EMPLOYEE_ID   INT PRIMARY KEY,
  DEPARTMENT_ID INT,
  EMPLOYEE_NAME    VARCHAR(20) NOT NULL,
  EMPLOYEE_ROLE    VARCHAR(25) NOT NULL,
  EMPLOYEE_EMAIL    VARCHAR(25),
  EMPLOYEE_PHONE    VARCHAR(20),
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES TPDEPARTMENT(DEPARTMENT_ID)  
);

CREATE TABLE TPSALES_CHANNEL(
  S_CHANNEL_ID INT,
  CHANNEL_NAME    VARCHAR(38)
);
alter table tpsales_channel add primary key(S_CHANNEL_ID);

CREATE TABLE TPINVOICE (
  INVOICE_ID INT,
  PRODUCT_ID INT,
  CUSTOMER_ID INT,
  S_CHANNEL_ID   INT,
  SALES_REP_ID INT,
  INV_DATE    DATE,
  CITY VARCHAR(50),
  STATE VARCHAR(50),
  REGION VARCHAR (50),
  QUANTITY INT
);

alter table tpinvoice add primary key (invoice_id, product_id);
alter table tpinvoice add FOREIGN KEY(product_ID) REFERENCES tpproduct(product_ID);
alter table tpinvoice add FOREIGN KEY(CUSTOMER_ID) REFERENCES TPCUSTOMER(CUSTOMER_ID);
alter table tpinvoice add foreign key(sales_rep_id) references tpemployee (employee_id);
alter table tpinvoice add FOREIGN KEY(S_CHANNEL_ID) REFERENCES TPSALES_CHANNEL(S_CHANNEL_ID);


